#!/bin/bash
#

_main() {
win="$(lsw)"
    if [[ $win ]]; then
	    hsetroot -fill $HOME/.backgrounds/.jpeg/17.jpeg -blur 15
    else
	    hsetroot -fill $HOME/.backgrounds/.jpeg/17.jpeg
    fi
 }

#loop it
while true ; do
    echo $(_main)
    sleep 1
done > /dev/null 2>&1
