#! /bin/sh

source $(dirname $0)/config
sxhkd &
#~/.fehbg &
(sleep 3 && conky) &
#(sleep 1 && mpd) &
#compton --config ~/.config/compton.conf &
#(sleep 2 && conky -q -c /home/okiptkn/.config/conky/conkyT.conf) &

#bspc monitor -d $(echo -e '\ue1ec') $(echo -e '\ue1f0') $(echo -e '\ue1ee') $(echo -e '\ue1e5') $(echo -e '\ue04d') $(echo -e '\ue1c4')
bspc config border_width        10
bspc config window_gap          10
bspc config focused_border_color '#8C4C4C'
bspc config normal_border_color  '#8F8F75' #313031

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc monitor -d I II III IV V VI

bspc rule -a Firefox desktop=^3
bspc rule -a mpv state=floating
bspc rule -a feh state=floating
bspc rule -a Geany desktop=^4

#[ -e "$PANEL_FIFO" ] && bspc subscribe report > "$PANEL_FIFO" &
#pgrep -x panel > /dev/null || ~/.config/bspwm/panel &> /tmp/panel.log
$(dirname $0)/panel &

# MPD daemon start (if no other user instance exists)
#[ ! -s ~/.config/mpd/pid ] && mpd
