#! /bin/sh

#HEIGHT=27
#PANEL_HEIGHT=24
PANEL_GEO="1300x27+33+10"
PANEL_GEO2="1366x24+0+0"
PANEL_GEO3="1190x20+176+0"
PANEL_FIFO=~/.temp/panel-fifo
PANEL_FONT="-*-fixed-medium-*-*-*-10-*-*-*-*-*-*-*"
#FONT="-*-fixed-medium-*-*-*-10-*-*-*-*-*-*-*"
#FONT="-*-dina-medium-r-*-*-10-*-*-*-*-*-*-*"
FONT_ICON="-wuncon-siji-medium-r-normal--10-100-75-75-c-80-iso10646-1"
PANEL_WM_NAME=bspwm_panel

#panel_colors
COLOR_DEFAULT_FG="#C4BFBF"					#a7a5a5
COLOR_DEFAULT_BG="#333232"						#333232		#282522
COLOR_MONITOR_FG="#8dbcdf"
COLOR_MONITOR_BG="#333232"
COLOR_FOCUSED_MONITOR_FG="#b1d0e8"
COLOR_FOCUSED_MONITOR_BG="#144b6c"
COLOR_FREE_FG="#000000"							#737171
COLOR_FREE_BG="#333232"
COLOR_FOCUSED_FREE_FG="#8B8989"			##000000		#a7a5a5
COLOR_FOCUSED_FREE_BG="#504e4e"         #free selector
COLOR_OCCUPIED_FG="#a7a5a5"
COLOR_OCCUPIED_BG="#333232"
COLOR_FOCUSED_OCCUPIED_FG="#d6d3d2"
COLOR_FOCUSED_OCCUPIED_BG="#504e4e"    #occupied selector
COLOR_URGENT_FG="#f15d66"
COLOR_URGENT_BG="#333232"
COLOR_FOCUSED_URGENT_FG="#501d1f"
COLOR_FOCUSED_URGENT_BG="#d5443e"
COLOR_STATE_FG="#89b09c"
COLOR_STATE_BG="#333232"
COLOR_TITLE_FG="#a8a2c0"
COLOR_TITLE_BG="#333232"
COLOR_SYS_FG="#b1a57d"
COLOR_SYS_BG="#333232"

# icons
GENTOO="\ue1ec"
ARCH="\ue00e"
CSTART="\ue00d"
CSOUND="\ue04d"
CVOLUME="\ue204"
CMAIL="\ue070"
CRAM="\ue19a"
CCPU="\ue021"
CNET="\ue04b"
CWIFI="\ue222"
CWIFI2="\ue1af"
TAG="\ue1db"
PAC="\ue0c6"
PAC2="\ue0aa"
# Time
CTIME="\ue018"
CPACK="\ue1b7"
CCLOCK="\ue016"
# panel center
CNONE="\ue0c0"
CFULL="\ue0c1"
# icons panel music
CPREV="\ue055"
CNEXT="\ue05b"
CPAUSE="\ue059"
CPLAY="\ue058"
CPAUSE2="\ue09b"
CPLAY2="\ue058"
CNEXT2="\ue05a"
CPREV2="\ue096"
CSTOP="\ue099"
MUSICON="\ue271"
CMUSIC="\ue1a6"
# icon volume
VPLUS="\ue06c"
VMINUS="\ue06d"
# battery or AC
BAT100="\ue254"
BAT70="\ue252"
BAT50="\ue250"
BAT30="\ue24f"
BAT15="\ue24e"
BAT7="\ue24c"
CAC="\ue215"

# $(pAction ${fg} ${bg} ${${command} ${whatprint})
pAction() {
    echo "%{F$1}%{B$2}%{A:$3:}$(printf '%b' $4)%{A}%{B-}%{F-}"
}

pAction2() {
	echo "%{F$1}%{B$2}%{A:$3:}%{A3:$4:}$(printf '%b' $5)%{A}%{A}%{B-}%{F-}"
}
# $(pActionUnderline ${fg} ${bg} ${underline} ${${command} ${whatprint})
pActionUnderline() {
    echo "%{F$1}%{B$2}%{U$3}%{+u}%{A:$4:}$(printf '%b' $5)%{A}%{-u}%{B-}%{F-}"
}

# $(pIcon ${color} ${icon})
pIcon() {
    echo "%{F$1}$(printf '%b' $2)%{F-}"
}

# $(pIconUnderline ${color} ${color_underline} ${icon})
pIconUnderline() {
    echo "%{F$1}%{U$2}%{+u}$(printf '%b' $3)%{-u}%{F-}"
}

# $(pText ${color} ${text})
pText() {
    echo "%{F$1}$2%{F-}"
}

# $(pTextUnderline ${color} ${color_underline} ${text})
pTextUnderline() {
    echo "%{F$1}%{U$2}%{+u}$3%{-u}%{F-}"
}

getXresColor() {
   echo "$( xrdb -query | grep $1: | grep -oE '#[a-zA-Z0-9]{6}' | cut -c 1- )"
}

# colors
BLACK="$(getXresColor color0)"
BLACK2="$(getXresColor color8)"
RED="#D64937"
RED2="$(getXresColor color9)"
GREEN="$(getXresColor color2)"
GREEN2="$(getXresColor color10)"
YELLOW="$(getXresColor color3)"
YELLOW2="$(getXresColor color11)"
BLUE="$(getXresColor color4)"
BLUE2="$(getXresColor color12)"
GRAY3="#A7A5A5"
GRAY="#848484"
BLACKBAR="#333232"
GRAY2="#737171"
CYAN="$(getXresColor color6)"
CYAN2="$(getXresColor color14)" 
WHITE="$(getXresColor color7)"
WHITE2="$(getXresColor color15)"

#colors2
biruL="#88D8B0"
oranye="#FFCC5C"
abangN="#FF6F69"
panila="#FFEEAD"
biruL2="#96CEB4"
oranyeD="#EB6E44"
ijo="#D3E397"
biruD2="#578C7A"
ijoD="#8B8F5C"
abangD="#8C6252"
panilaD="#8F8F75"
unguD="#855178"
ijoD2="#838A60"
ijoD3="#A3BE8C"
biruD3="#4C626D"
biruD4="#6A7A8F"
unguD2="#7D6A79"
abangD2="#8C4C4C"
putih="#C4BFBF"
ireng="#282522"
coklat="#907245"
abangL="#EF6762"

#BG="$(getXresColor background)"
#FG="$(getXresColor foreground)"

SEP=" "
