#!/bin/sh
#

# [clipboard] dmenu script to launch clipmenu
# requires cdown's clipmenu (https://github.com/cdown/clipmenu/)

clipb="clipmenu -p '------------| clipboard |-----------' -fn 'Liberation Mono:pixelsize=13' -i -l 5 -y 80 -x 800 -w 300 -nb '#05111D' -sb '#5F2B57' -nf '#CCCCCC' -sf '#FFFFFF'"

cmd=$(eval $clipb)

exit 0
