#!/bin/sh
#

# [instacli] dmenu script to launch a cli program on the go

# Volume Status for alsa users
#volume="$(amixer get Master | tail -1 | sed 's/.*\[\([0-9]*%\)\].*/\1/')"

# Define your preferred terminal
terminal='st'

# How many spaces do you want before the battery status ?
spaces=9

# Automating the number of spaces
function auto_space
{
for ((i = 0; i <= $spaces; i++)); do
    printf ' '
done
}

# Menu Order.
menu_list="vim\nranger\nncmpcpp\ntask"

# Dmenu Preferences
Dmenu="dmenu_run -p '------------| insta cli |-----------' -fn 'Liberation Mono:pixelsize=13' -i -l 5 -y 80 -x 800 -w 300 -nb '#05111D' -sb '#870A27' -nf '#CCCCCC' -sf '#FFFFFF'"

cmd=$(echo -e "$menu_list" | eval $Dmenu)

case $cmd in
    vim)
        $terminal vim ;;
    ranger)
        $terminal ranger ;;
    task)
        $terminal top ;;
    ncmpcpp)
        $terminal ncmpcpp ;;
esac
exit 0
