#!/bin/bash
#

#
# [netspeedmonitor] a simple shell script to print current network speed, requires lemonbar for pop up
# 
# more@ github.com/okiptkn
#
# (c) 2018 <Restu Purnomo>
# Licensing stuff : By the name of the Dark Lord Satania-sama, I hereby granted you the permissions 
# to do whatever the fuck it is you want to do with this script. No warranty or whatsoever provided.
# 

_popname="network"

_netw() {
  int="wlp3s0b1" # set your wifi interface
  downr=`cat /sys/class/net/$int/statistics/rx_bytes`
  upt=`cat /sys/class/net/$int/statistics/tx_bytes`
  
   sleep 1
   
  downn=`cat /sys/class/net/$int/statistics/rx_bytes`
  upn=`cat /sys/class/net/$int/statistics/tx_bytes`
  countr=`expr $downn - $downr`
  countt=`expr $upn - $upt`
  up=`expr $countt / 1024`
  down=`expr $countr / 1024`

  # rx = downspeed
  # tx = upspeed
   echo "up $up kBps | down $down kBps"
  }   

_pipetolemon() {
    while true ; do
        echo "%{c}$(_netw)"
        sleep 1
    done |\
        lemonbar -d -n "${_popname}" -g 200x40+20+40 -F "#C4BFBF" -B "#05111D"
  }

_main() {
        $(_pipetolemon) & read -t 5 ; pkill netspeedmonitor &2>/dev/null
  }
    
_main"$@"
