#!/usr/bin/env bash

# [passmanager] dmenu script for managing gpg encrypted password
# requires pass (https://www.passwordstore.org/)

shopt -s nullglob globstar

typeit=0
if [[ $1 == "--type" ]]; then
	typeit=1
	shift
fi


STARTDIR=${PASSWORD_STORE_DIR-~/.password-store}
BASEDIR=$STARTDIR
DONE=0
LEVEL=0
PREVSELECTION=""
SELECTION=""

while [ "$DONE" -eq 0 ] ; do 
  password_files=( "$STARTDIR"/* )
  password_files=( "${password_files[@]#"$STARTDIR"/}" )
  password_files=( "${password_files[@]%.gpg}" )
  
  if [ "$LEVEL" -ne 0 ] ; then
    password_files=(".." "${password_files[@]}") 
  fi
  entry=$(printf '%s\n' "${password_files[@]}" | dmenu "$@" -p '------------| password |------------' -fn 'Liberation Mono:pixelsize=13' -i -l 5 -y 80 -x 800 -w 300 -nb '#05111D' -sb '#9B2859' -nf '#CCCCCC' -sf '#FFFFFF')
  
  echo "entry: $entry"
  if [ -z $entry ] ; then
    DONE=1
    exit
  fi
  
  if [ "$entry" != ".." ] ; then
    PREVSELECTION=$SELECTION
    SELECTION="$SELECTION/$entry"
  
    # check if another dir
    if [ -d "$STARTDIR/$entry" ] ; then
      STARTDIR="$STARTDIR/$entry"
      LEVEL=$((LEVEL+1))
    else
      # not a directory so it must be a real password entry
  
      if [[ $typeit -eq 0 ]]; then
        pass show -c "$SELECTION" 2>/dev/null
      else
        xdotool - <<<"type --clearmodifiers -- $(pass show "$SELECTION" | head -n 1)"
      fi
      DONE=1
    fi
  
  else
    LEVEL=$((LEVEL-1))
    SELECTION=$PREVSELECTION
    STARTDIR="$BASEDIR/$SELECTION"
  fi
done

