#!/bin/bash
#

# this script was meant to be used along side my dmenu's instacmd script
# upon executing it, this script will open a terminal and prompt an interactive dialog
# also note that this script simply uses [su] command to execute the [wpa_supplicant] command within root environment, 
# depends on your setup you might want to edit the main command to suits your setup

# more@ github.com/okiptkn
#
# (c) 2018 <Restu Purnomo>
# Licensing stuff : By the name of the Dark Lord Satania-sama, I hereby granted you the permissions 
# to do whatever the fuck you want to do with this script. No warranty or whatsoever provided.
# 
# TODO : learn [wpa_supplicant] command for more scriptable features

# write function
_main() {
while true; do
    echo 'wifi connect script...'
    sleep 1
    echo 'choose your wifi router'
    sleep 1
    read -p 'which one would you want to connect : wifi rumah "r" or kantor "k" (type "q" to quit this dialog) : ' rkq

    case $rkq in

        [Rr]* ) echo 'attempting to connect at wifi rumah...'
            sleep 1
            echo 'enter your root password'
            su -c 'wpa_supplicant -B -i yourwifiinterface -c <(wpa_passphrase rumahssid rumahpass)'
            sleep 1
            echo 'exiting wifiscript... '
            sleep 1
            break;;

        [Kk]* ) echo 'attempting to connect at wifi kantor...'
            sleep 1
            echo 'enter your root password'
            su -c 'wpa_supplicant -B -i yourwifiinterface -c <(wpa_passphrase kantorssid kantorpass)'
            sleep 1 
            echo 'exiting wifiscript... '
            sleep 1
            break;;

        [Qq]* ) exit;;

        * ) echo 'type "q" to quit this dialog';;

    esac
done
}

_main"$@"
